[phases.setup]
nixPkgs = ["nodejs-18_x", "python310", "pip"]

[phases.install]
cmds = [
  "cd backend && npm install",
  "cd backend && python3 -m pip install -r requirements.txt"
]

[start]
cmd = "cd backend && node server.js"
