[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.ignore]
ignore = ["node_modules", ".git", "src", "assets", "*.md"]
