[phases.setup]
nixPkgs = ["nodejs-18_x", "python310"]

[phases.install]
cmds = [
  "npm install",
  "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && PIP_BREAK_SYSTEM_PACKAGES=1 python3 get-pip.py",
  "python3 -m pip install --break-system-packages -r requirements.txt"
]

[start]
cmd = "node server.js"
